services:
  - type: web
    name: pdf-chat-app
    env: python
    plan: free
    buildCommand: |
      cd backend && pip install -r requirements.txt
    startCommand: |
      cd backend/app && python main.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
